baseURL = "https://nav.sch246.com/"
languageCode = "zh-CN"
title = "sch246’s nav"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""
[params]
  author = "iplaycode"
  description = "Webstack Hugo"
[params.search]
  enable = false
[params.darkmode]
  enable = false